// lib/features/community/test_data_service.dart
import 'community_model.dart';

class TestDataService {
  static List<CommunityReportModel> getTestReports() {
    return [
      CommunityReportModel(
        id: 'test_1',
        title: 'Road Accident - Main Street',
        description: 'Two-vehicle collision reported at Main Street intersection. Emergency services on site. Traffic diverted via alternate routes.',
        reportType: 'emergency',
        severity: 'high',
        location: 'Lusaka Central',
        timestamp: DateTime.now().subtract(const Duration(minutes: 15)),
        author: 'Lusaka Police Department',
        isVerified: true,
        viewCount: 234,
        latitude: -15.4167,
        longitude: 28.2833,
        distanceFromUser: 1.2,
      ),
      CommunityReportModel(
        id: 'test_2',
        title: 'Community Safety Alert',
        description: 'Increased police patrols in residential areas this evening. Please report any suspicious activity immediately.',
        reportType: 'announcement',
        severity: 'medium',
        location: 'Woodlands',
        timestamp: DateTime.now().subtract(const Duration(hours: 2)),
        author: 'Community Safety Office',
        isVerified: true,
        viewCount: 567,
        latitude: -15.3894,
        longitude: 28.3134,
        distanceFromUser: 3.5,
      ),
      CommunityReportModel(
        id: 'test_3',
        title: 'Missing Child Found Safe',
        description: 'The 8-year-old child reported missing earlier today has been found safe and reunited with family. Thank you to everyone who helped spread the word.',
        reportType: 'crime',
        severity: 'low',
        location: 'Kabulonga',
        timestamp: DateTime.now().subtract(const Duration(hours: 5)),
        author: 'Police Community Relations',
        isVerified: true,
        viewCount: 1203,
        latitude: -15.4500,
        longitude: 28.2500,
        distanceFromUser: 2.8,
      ),
      CommunityReportModel(
        id: 'test_4',
        title: 'CRITICAL: Fire Emergency',
        description: 'Active fire response at industrial area. Residents advised to avoid the area. Road closures in effect on Industrial Road.',
        reportType: 'emergency',
        severity: 'critical',
        location: 'Industrial Area',
        timestamp: DateTime.now().subtract(const Duration(minutes: 45)),
        author: 'Fire & Rescue Services',
        isVerified: true,
        viewCount: 890,
        latitude: -15.4300,
        longitude: 28.2900,
        distanceFromUser: 4.2,
      ),
      CommunityReportModel(
        id: 'test_5',
        title: 'Community Meeting - Crime Prevention',
        description: 'Join us for a community meeting on Thursday at 6 PM at the Community Center. Topics include neighborhood watch programs and crime prevention strategies.',
        reportType: 'event',
        severity: 'low',
        location: 'Rhodes Park',
        timestamp: DateTime.now().subtract(const Duration(days: 1)),
        author: 'Neighborhood Watch',
        isVerified: true,
        viewCount: 342,
        latitude: -15.4100,
        longitude: 28.3000,
        distanceFromUser: 5.1,
      ),
    ];
  }
}
